const configuration = {
    title: 'My Blog Title',                                                 // (* Required)
    description: 'This is a blog generated by Gatsby with borderless',      // (* Required)
    author: 'Author Name',                                                  // (* Required)
    language: 'en-US',                                                      // (* Required) html lang; ex. 'en' | 'en-US' | 'ko' | 'ko-KR' | ...
    siteUrl: 'https://my_site_url.com',                                     // (* Required)
    // ex.'https://junhobaik.github.io'
    // ex.'https://junhobaik.github.io/' << X, Do not enter "/" at the end.

    bio: {
        profileImageFileName: '',                   // include filename extension ex.'profile.jpg'
        // The Profile image file is located at path "./images/"
        // If the file does not exist, it is replaced by a random image.
        comment: 'I am a front-end engineer',
        name: 'My name',
        location: 'Earth, Milky Way Galaxy',
        email: '@aol.com',
        social: JSON.stringify({  // stringify for easier way to query
            // the param should be like =>     key: 'https://link'
            // `key` should be able to find in fontawesomeicons / brands
            // check it out at 'https://fontawesome.com/search?o=r&f=brands'
            'github': 'https://github.com/junhobaik/',
            // linkedin: '',
            // facebook: '',
            // instagram: '',
            // bilibili: '',
            // twitter: '',
            // tiktok: '',
            // youtube: '',
            // line: '',
            // whatsapp: '',
            // telegram: '',
            // pinterest: '',
            // zhihu: '',
            // weibo: '',
            // behance: '',
            // twitch: '',
        })
    },
    post: {
        enablePostOfContents: false,
        disqusShortname: '',
        enableSocialShare: false,
    },

    googleAD_on: false,

    googleAD: {
        googleSearchConsole: '',
        googleAdsenseSlot:   '',
        googleAdsenseClient: '',
    },

    googleAnalytics: ''
};

module.exports = configuration;

// exports.config = config;
